export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_FAILED = 'REVIEW_LIST_FAILED';

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST';
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_FAILED = 'REVIEW_DELETE_FAILED';

export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST';
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATE_FAILED = 'REVIEW_CREATE_FAILED';
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET';

export const REVIEW_UPDATE_REQUEST = 'REVIEW_UPDATE_REQUEST';
export const REVIEW_UPDATE_SUCCESS = 'REVIEW_UPDATE_SUCCESS';
export const REVIEW_UPDATE_FAILED = 'REVIEW_UPDATE_FAILED';
export const REVIEW_UPDATE_RESET = 'REVIEW_UPDATE_RESET';