export const SUBCRIPTION_LIST_REQUEST = 'SUBCRIPTION_LIST_REQUEST';
export const SUBCRIPTION_LIST_SUCCESS = 'SUBCRIPTION_LIST_SUCCESS';
export const SUBCRIPTION_LIST_FAILED = 'SUBCRIPTION_LIST_FAILED';

export const SUBCRIPTION_AMOUNT_REQUEST = 'SUBCRIPTION_AMOUNT_REQUEST';
export const SUBCRIPTION_AMOUNT_SUCCESS = 'SUBCRIPTION_AMOUNT_SUCCESS';
export const SUBCRIPTION_AMOUNT_FAILED = 'SUBCRIPTION_AMOUNT_FAILED';

export const SUBCRIPTION_AMOUNT_UPDDATE_REQUEST = 'SUBCRIPTION_AMOUNT_UPDDATE_REQUEST';
export const SUBCRIPTION_AMOUNT_UPDDATE_SUCCESS = 'SUBCRIPTION_AMOUNT_UPDDATE_UCCESS';
export const SUBCRIPTION_AMOUNT_UPDDATE_FAILED = 'SUBCRIPTION_AMOUNT_UPDDATE_FAILED';

export const SUBCRIPTION_STATISTIC_REQUEST = 'SUBCRIPTION_STATISTIC_REQUEST';
export const SUBCRIPTION_STATISTIC_SUCCESS = 'SUBCRIPTION_STATISTIC_SUCCESS';
export const SUBCRIPTION_STATISTIC_FAILED = 'SUBCRIPTION_STATISTIC_FAILED';

export const SUBCRIPTION_CHECK_REQUEST = 'SUBCRIPTION_CHECK_REQUEST';
export const SUBCRIPTION_CHECK_SUCCESS = 'SUBCRIPTION_CHECK_SUCCESS';
export const SUBCRIPTION_CHECK_FAILED = 'SUBCRIPTION_CHECK_FAILED';

export const SUBCRIPTION_REQUEST = 'SUBCRIPTION_REQUEST';
export const SUBCRIPTION_SUCCESS = 'SUBCRIPTION_SUCCESS';
export const SUBCRIPTION_FAILED = 'SUBCRIPTION_FAILED';

